version: '3.7'

services:
  postgres:
    image: postgres:14-alpine3.14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=app_admin
      - POSTGRES_PASSWORD=app_password
    ports:
      - "5432:5432"